ipv4 = true
ipv6 = false
nat = true
log = file
loglevel = info

[http]
enabled = true
address = 127.0.0.1
port = 7071

[sam]
enabled = true
address = 127.0.0.1
port = 7656

[socksproxy]
enabled = true
address = 127.0.0.1
port = 4447

[reseed]
verify = true
